[package]
name = "win-win"
version = "0.1.1"
authors = ["Raph Levien <raph.levien@gmail.com>"]
license = "MIT/Apache-2.0"
categories = ["os::windows-apis", "gui"]
readme = "README.md"
description = "A semi-opinionated way to create windows on Windows."
repository = "https://github.com/raphlinus/win-win"
edition = "2018"

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
all-features = true

[features]
kb = ["keyboard-types"]

[dependencies.windows]
version = "0.23.0"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging"
]

[dependencies.keyboard-types]
version = "0.5.0"
optional = true
default-features = false

[dependencies]
wio = "0.2.2"
